api_keys_path: "/home/mila/b/baldelld/scratch/.api_keys"

data:
  base_dir: "/network/scratch/b/baldelld/LLM4CAD/cadmium/data/"
  original_annotations: "${data.base_dir}/text2cad_v1.1/text2cad_v1.1.csv"
  validation_qwen_tokenized_parquet_path: "${data.base_dir}/text2cad_v1.1/validation_json_qwen_tokenized.parquet"
  output_dir: "${data.base_dir}/gpt_annotations/"

model:
  model_id: "gpt-4.1"
