#!/bin/bash
#SBATCH --job-name=train_cadmum
#SBATCH --output=output/experiment-%A.%a.out
#SBATCH --error=error/experiment-%A.%a.err
#SBATCH --time=0-03:00:00
#SBATCH --nodes=1                       
#SBATCH --gpus-per-task=4               
#SBATCH --cpus-per-task=24              
#SBATCH --mem=0                         
#SBATCH --ntasks-per-node=1             
#SBATCH --constraint=80gb               
#SBATCH --exclude=cn-k[001-002]
#SBATCH --partition=short-unkillable

module load anaconda/3
export HF_HOME=$SCRATCH/LLM4CAD
conda activate $SCRATCH/cadmium
export OMP_NUM_THREADS=4

# Start training in background
srun torchrun --nproc_per_node=4 cadmium/src/train.py --config-name train