#!/bin/bash
#SBATCH --job-name=serve_llama4
#SBATCH --output=output/experiment-%A.%a.out
#SBATCH --error=error/experiment-%A.%a.err
#SBATCH --time=0-03:00:00
#SBATCH --nodes=1
#SBATCH --gpus-per-task=4
#SBATCH --cpus-per-task=12
#SBATCH --mem=512gb
#SBATCH --ntasks-per-node=1
#SBATCH --exclude=cn-k[001-002]
#SBATCH --partition=short-unkillable
#SBATCH --constraint=80gb

module load anaconda
conda activate $SCRATCH/cadmium

python render.py