#!/bin/bash
#SBATCH --job-name=data_prep
#SBATCH --output=output/experiment-%A.%a.out
#SBATCH --error=error/experiment-%A.%a.err
#SBATCH --time=0-06:00:00
#SBATCH --nodes=1                       # number of nodes
#SBATCH --gpus-per-task=4               # number of gpus per node
#SBATCH --cpus-per-task=24              # number of cpus per gpu
#SBATCH --mem=128Gb                         # all memory per node
#SBATCH --ntasks-per-node=1             # crucial - only 1 task per node!
#SBATCH --partition=lab-chandar

module load anaconda/3
export HF_HOME=$SCRATCH/LLM4CAD
conda activate $SCRATCH/cadmium2

torchrun process_data.py 
