#!/bin/bash
#SBATCH --job-name=train_text2cad
#SBATCH --output=output/experiment-%A.%a.out
#SBATCH --error=error/experiment-%A.%a.err
#SBATCH --time=0-03:00:00
#SBATCH --nodes=1                       # number of nodes
#SBATCH --gpus-per-task=4               # number of gpus per node
#SBATCH --cpus-per-task=24              # number of cpus per gpu
#SBATCH --mem=0                         # all memory per node
#SBATCH --ntasks-per-node=1             # crucial - only 1 task per node!
#SBATCH --constraint=80gb               # constraints
#SBATCH --exclude=cn-k[001-002]
#SBATCH --partition=short-unkillable

module load anaconda/3
export HF_HOME=$SCRATCH/LLM4CAD
conda activate $SCRATCH/cadmium2
export OMP_NUM_THREADS=4

experiment_name="2025-05-12-00"

checkpoint_dir="../experiments/${experiment_name}/"

# Get initial latest checkpoint directory
latest_checkpoint=$(ls -td ${checkpoint_dir}/checkpoint-* 2>/dev/null | head -n 1)

# Start training in background
srun torchrun --nproc_per_node=4 train_texttojson_2.py --config-name ${experiment_name} #&